<?php
//前台模版
class mod_juzi extends pagefront
{
    function doAction()
    {
        parent::doAction(); // TODO: Change the autogenerated stub


        $db = mysql::getInstance();
        switch( $this->getOption('do')) {
            //获取单篇数据
            case 'get_one_data':
                $id = $this->getOption("id", '0', 'int');
                if(!$id) return $this->error('no id');
                $data = DbBase::getRowBy('juzi', '*', "id={$id}");
                return Message::getMsgJson('0038', $data);
            break;
                //获取列表
            case 'get_sql_data':
                $can_get_tables = [
                    's_articles','s_articles_types', 'juzi', 'c_user'
                ];
                $this->getOption('table|admin_power', '', 'trim');  //table|admin_power=a 或 b|a.teml_id = b.id|l/r/i/f
                $where_ = $this->getOption("where"); //user.is_show = 1 and user_id={uid}
                $fields = $this->getOption("fields"); // a.id,a.username,b.aa,b.asss
                $page = $this->getOption("page", 1, 'int');
                $size = $this->getOption("size", 10, 'int');
                $order = $this->getOption("order", '', 'trim'); // order_id desc
                $listData = [];
                $msg = '获取成功';
                if(!$can_get_tables) return $this->error('没有设置支持查询的表格');
                $result = func::uri_getResult($_POST, $this, $db, $can_get_tables);
                $msg = $result[1];
                $listData = $result[2];
                $pageData = $result[3];
                $whereData = $result[4];
//                print_r($result);exit;
                $data = array_merge(['list_data'=>$listData], ['page_data'=> $pageData], ['where'=> $whereData]);
                if(!isset($result[0]) || $result[0] !== 1) {
                   return $this->error('获取失败');
                } else {
                    return Message::getMsgJson('0038', $data);
                }
            break;
        }
    }

    //得到显示页数据
    function getData()
    {
        $db = mysql::getInstance();
        $db->getQuery();
        switch( $this->getOption('show')) {
            case 'read':
                $router = $this->getOption('router'); // : /post/1/
                if($router) {
                    $id = trim(explode('juzi/read/', $router)[1]);
                    $id = trim($id, '/');
                    if(!$id) {
                        Message::Show('no id');
                        exit;
                    }
                } else {
                    Message::Show('no router');
                    exit;
                }
                $juziInfo = DbBase::getRowBy('juzi', 'id,title,uid,hit,ctime', 'id='. $id);
                if(!$juziInfo) {
                    Message::Show('句子不存在');
                    exit;
                }
                //浏览+1
                if(!$db::ifHit('li6_juzi_read',$id)) {
                    $newdata = [];
                    $newdata['hit'] = $juziInfo['hit'] + 1;
                    DbBase::updateByData('juzi', $newdata, 'id='.$id);
                }
                $arr = $juziInfo;
                $arr['ctime'] = Timer::now($juziInfo['ctime']);
                $arr['author'] = Users::getUserNick($juziInfo['uid']);
                $htmlname = 'front/read_juzi.php';
                break;
            default:
                $htmlname = 'front/juzi.php';
                break;
        }
        //读取页头 页尾
        $arr['header'] = $this -> readTemp('/front/header.php');
        $arr['footer'] = $this -> readTemp('/front/footer.php');
        //组织显示数据
        $this->setTempData ($arr);
        $this->setTempPath($htmlname);//设置模板
    }
}